dgs.graphql.schema-locations: classpath:graphql/*.graphql*
spring:
  docker:
    compose:
      enabled: true
      skip:
        in-tests: false
      file: src/main/docker/docker-compose.yml
      lifecycle-management: start_only
      readiness:
        wait: never
  cloud:
    zookeeper:
      connect-string: localhost:2181
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  graphql:
    schema:
      locations: classpath:graphql/*.graphql*